name: Build and deploy

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Check-out different repository with blog posts and other content
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.actor }}/website-content
          path: website-content
          ref: master

      - name: Create .env file
        run: |
          touch .env
          echo VITE_EXTERNAL_IMAGE_BASE_URL=${{ secrets.VITE_EXTERNAL_IMAGE_BASE_URL }} >> .env
          
      - name: Debug ls commands
        run: |
          echo "ls"
          ls
          echo "ls $GITHUB_WORKSPACE"
          ls $GITHUB_WORKSPACE

      - name: Setup PNPM and install dependencies
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.12.2
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
            
      - name: Build Sveltekit app
        run: pnpm build

      - name: Publish on Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
