name: Build and deploy

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Sveltekit build
        run: npm run build
        
      - name: Deploy on Netlify
        run: echo "TODO integrate with Netlify"
